map_update_interval: 2.0  
maxUrange: 15.0     # 3.0
sigma: 0.05         # 0.1
kernelSize: 5       # 1
lstep: 0.05   
astep: 0.05
iterations: 10    # 5
lsigma: 0.05      # 0.075
ogain: 1.5        # 3.0
lskip: 1          # 0
minimumScore: 300 # 50
srr: 0.025        # 0.1
srt: 0.05         # 0.2
str: 0.025
stt: 0.05
linearUpdate: 2.0      # 1.0
angularUpdate: 2.0     # 0.2
temporalUpdate: 3.0    # 0.5
resampleThreshold: 0.3 # 0.5
particles: 200 # 100
xmin: -10.0
ymin: -10.0
xmax: 10.0
ymax: 10.0
delta: 0.05
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
